spring.application.name=tasks-api
server.port=8080

# Database config
spring.datasource.url=jdbc:postgresql://localhost:5432/tasksdb
spring.datasource.username=${DB_USERNAME:tasksuser}
spring.datasource.password=${DB_PASSWORD:taskspass}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

jwt.secret=your-super-secret-key-that-is-at-least-32-characters-long
jwt.expiration=86400000